### ISSUE TITLE
Ethercluster ETH endpoint doesn't work with Jade Explorer RPC URL

### ISSUE THREAD

**Issue by YazzyYaz** [etclabscore/expedition#102]
**Describe the bug**
Using https://eth.ethercluster.com/ doesn't pull the data for the ETHereum endpoint

**To Reproduce**
Go to this URL https://explorer.jade.builders/?rpcUrl=https://eth.ethercluster.com/
You'll notice it doesn't pull latest data and it errors out in the DevTools Console.

**Expected behavior**
It should pull explorer data for ETH chain

**Comment by virgil** [comment]
Thanks hon.  Here's how to use it:

https://developers.cloudflare.com/distributed-web/ethereum-gateway/interacting-with-the-eth-gateway/

**Comment by zcstarr** [comment]
@virgil @YazzyYaz  the endpoint doesn't seem to support batch

```
curl -H "Content-Type: application/json" -X POST --data '[{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "web3_clientVersion",
  "params": []
}]' https://eth.ethercluster.com
```

**Comment by shanejonas** [comment]
heres another endpoint having some issues:

https://explorer.jade.builders/?rpcUrl=https://mainnet.infura.io/v3/4a17e6f0c78347a7ac1e2434124125af


![image](https://user-images.githubusercontent.com/364566/66936126-08c89d00-eff2-11e9-86c8-c565ad868fef.png)

**Comment by shanejonas** [comment]
bump, still giving the same error:
```
$ curl -H "Content-Type: application/json" -X POST --data '[{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "web3_clientVersion",
  "params": []
}]' https://eth.ethercluster.com
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request"}}%
```
