### ISSUE TITLE
block hash overflows card in card list view

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/expedition#228]
**Describe the bug**
block hash overflows card in card list view

**Screenshots**
![2020-01-10-113151_878x286_screenshot](https://user-images.githubusercontent.com/45600330/72173349-f49bfe00-339c-11ea-8bca-12dd63cd36d0.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 96e603ef6a9f982455fb9166177f5e61b8c3a215

**Comment by shanejonas** [comment]
fixed in #230
