### ISSUE TITLE
handle bigInt with maxBy and minBy

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/expedition#439]
for calculating things like gasPrice min/maxes we are just using lodash. but probably doesnt support BigInt

**Comment by shanejonas** [comment]
![image](https://user-images.githubusercontent.com/364566/98494351-a42a4280-21f1-11eb-8676-b25725db4782.png)


seems like its just breaking prod

to reproduce go here:

https://expedition.dev/block/0x2eced4422d3146112c43a17a882cfb539d0a450602c7f73d9a216c68b589b545?network=ethereum

**Comment by hamedtayeban** [comment]
#hamed2f
